version: '3.8'

services:
  api:
    container_name: samoli-api
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - postgres
    environment:
        DATABASE_URL: postgres://root:root@postgres:5432/cms
    ports:
      - "3000:3000"

  postgres:
    container_name: samoli-db
    image: postgres:14.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: cms
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
#sudo lsof -i :5432
#sudo kill